In [2]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  fonts-nanum
0 upgraded, 1 newly installed, 0 to remove and 24 not upgraded.
Need to get 9,599 kB of archives.
After this operation, 29.6 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 fonts-nanum all 20180306-3 [9,599 kB]
Fetched 9,599 kB in 2s (6,285 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package fonts-nanum.
(Reading database ... 122349 files and directories currently installed.)
Preparing to unpack .../fonts-nanum_20180306-3_all.deb ...
Unpacking fonts-nanum (20180306-3) ...
Setting up fonts-nanum (20180306-3) ...
Processing triggers for fontconfig (2.13.1-2ubuntu3) ...
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 10 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no such directory
/root/.fonts: skipping, no such directory
/usr/share/fonts/truetype: skipping, looped directory detected
/usr/share/fonts/truetype/humor-sans: skipping, looped directory detected
/usr/share/fonts/truetype/liberation: skipping, looped directory detected
/usr/share/fonts/truetype/nanum: skipping, looped directory detected
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent cache directory
/root/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [1]:
from sklearn.preprocessing import scale
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline

In [4]:
wine=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/wine_test.csv')

In [6]:
wine=wine.drop('Unnamed: 0',axis=1)
wine

In [15]:
wine.isna().sum()
wine.dropna(inplace=True)

### KNN 알고리즘, Kmeans 
- KNN 지도학습(회귀, 분류), Kmenas 비지도학습
### K-means 
- k개를 지정하여 평균을 통해 군집화한다는 뜻으로 생각해 보자!
- 작동원리: 평균, 거리 기반(유클리디안) 
- 초기값을 지정해 줘야함, 몇 개의 군집을 선택해야 하는지 가이드를 주는 것이 어려움
- 단점: 거리 기반이기 때문에 나타나는 문제(이상치에 민감, 그룹 자체의 분산 반영X), 속도 느림
- 장점: 군집화에 가장 많이 활용, 이해 쉬움, 알고리즘 간결

In [16]:
# 클래스 별 갯수 확인
wine['class'].value_counts()

1    66
0    57
2    48
Name: class, dtype: int64

### KMeans 사용

In [13]:
kmeans=KMeans(n_clusters=3,init='k-means++',max_iter=300,random_state=111)
kmeans

KMeans(n_clusters=3, random_state=111)

In [17]:
wine_x=wine.drop('class',axis=1)
wine_x

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
5,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [18]:
kmeans.fit(wine_x)
print(kmeans.labels_)

/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 1 1 0 0 1 0 0 0 0 0 0 1 1 0 0
 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 1 2 1 2 2 1 2 2 1 1 2 2 0 1 2 2
 2 1 2 2 1 1 2 2 2 2 2 1 1 2 2 2 2 2 1 2 1 2 1 2 1 2 2 2 2 1 2 2 1 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 1 1 1 1 2 2 2 1 1 2 2 1 1 2 1 1 2 2 2 2 1 1
 1 2 1 1 1 2 1 2 1 1 2 1 1 1 1 2 2 1 1 1 1 1 2]

In [19]:
wine['cluster']=kmeans.labels_
wine

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,class,cluster
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,0,0
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,0,0
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,0,0
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,0,1
5,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,2,1
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,2,1
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,2,1
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,2,1
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,2,2

In [21]:
wine.groupby(['class','cluster'])['alcohol'].count()

class  cluster
0      0          44
       1          13
1      0           1
       1          17
       2          48
2      1          29
       2          19
Name: alcohol, dtype: int64

- 클래스 값과 비교했을 때 군집화가 잘 이루어지지 않음
- 변수가 많은 고차원 상태로 분석을 진행한 상태
- 중요한 변수만을 골라 다시 돌리는 것이 필요

### 변수 선택
- 클래스 별로 평균 차이가 큰 경우 이상치가 있을 것이라 판단 후 제외

In [23]:
col=list(wine.columns)

for i in col:
  print('-----------------',i ,'mean 비교')
  print(wine.groupby(['class'])[i].mean())

----------------- alcohol mean 비교
class
0    13.735263
1    12.294242
2    13.153750
Name: alcohol, dtype: float64
----------------- malic_acid mean 비교
class
0    2.021228
1    1.932121
2    3.333750
Name: malic_acid, dtype: float64
----------------- ash mean 비교
class
0    2.466140
1    2.245606
2    2.437083
Name: ash, dtype: float64
----------------- alcalinity_of_ash mean 비교
class
0    17.192982
1    20.257576
2    21.416667
Name: alcalinity_of_ash, dtype: float64
----------------- magnesium mean 비교
class
0    106.614035
1     93.454545
2     99.312500
Name: magnesium, dtype: float64
----------------- total_phenols mean 비교
class
0    2.844211
1    2.254848
2    1.678750
Name: total_phenols, dtype: float64
----------------- flavanoids mean 비교
class
0    2.986316
1    2.089545
2    0.781458
Name: flavanoids, dtype: float64
----------------- nonflavanoid_phenols mean 비교
class
0    0.290526
1    0.365152
2    0.447500
Name: nonflavanoid_phenols, dtype: float64
----------------- proanthocyanins mean 비교
class
0    1.908772
1    1.612879
2    1.153542
Name: proanthocyanins, dtype: float64
----------------- color_intensity mean 비교
class
0    5.554211
1    3.111970
2    7.396250
Name: color_intensity, dtype: float64
----------------- hue mean 비교
class
0    1.061930
1    1.066515
2    0.682708
Name: hue, dtype: float64
----------------- od280/od315_of_diluted_wines mean 비교
class
0    3.158947
1    2.789394
2    1.683542
Name: od280/od315_of_diluted_wines, dtype: float64
----------------- proline mean 비교
class
0    1118.105263
1     509.090909
2     629.895833
Name: proline, dtype: float64
----------------- class mean 비교
class
0    0.0
1    1.0
2    2.0
Name: class, dtype: float64
----------------- cluster mean 비교
class
0    0.228070
1    1.712121
2    1.395833
Name: cluster, dtype: float64

- alcohol/ash/nonflavanoid_phenols/proanthocyanins 선택

In [26]:
wine_xx=wine[['alcohol', 'ash', 'nonflavanoid_phenols' ,'proanthocyanins']]

kmeans.fit(wine_xx)
print(kmeans.labels_)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 2 2 1 1 1 1 1 1 1 1 2 2 2
 1 1 2 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 0 0 0 1 2 2 0 1 2 1 0 0 2
 0 0 0 0 0 0 2 0 2 0 0 0 0 0 0 2 0 0 0 0 0 0 0 2 0 0 0 2 0 0 0 2 0 0 0 0 0
 0 2 0 0 0 1 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 1 2
 2 1 2 1 1 2 2 2 2 2 2 1 2 1 2 2 2 1 2 2 2 2 1]

/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

In [28]:
wine['cluster2']=kmeans.labels_
wine.groupby(['class','cluster2'])['alcohol'].count()

class  cluster2
0      1           49
       2            8
1      0           47
       1            4
       2           15
2      0            1
       1            8
       2           39
Name: alcohol, dtype: int64

### 스케일링
- 거리 기반이기 때문에 값 차이에 민감
- 클러스터링 할 때 스케일링을 꼭 해야함!

In [29]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler,RobustScaler

wine_xx

     alcohol   ash  nonflavanoid_phenols  proanthocyanins
0      14.23  2.43                  0.28             2.29
2      13.16  2.67                  0.30             2.81
3      14.37  2.50                  0.24             2.18
4      13.24  2.87                  0.39             1.82
5      14.20  2.45                  0.34             1.97
..       ...   ...                   ...              ...
173    13.71  2.45                  0.52             1.06
174    13.40  2.48                  0.43             1.41
175    13.27  2.26                  0.43             1.35
176    13.17  2.37                  0.53             1.46
177    14.13  2.74                  0.56             1.35

[171 rows x 4 columns]

In [30]:
st_scaler=StandardScaler()
st_scaler.fit(wine_xx)

StandardScaler()

In [31]:
wine_sc=st_scaler.transform(wine_xx)
wine_sc

array([[ 1.52631422,  0.20782113, -0.66103228,  1.25092179],
       [ 0.18121398,  1.0807975 , -0.50249579,  2.17042222],
       [ 1.70230865,  0.46243924, -0.97810527,  1.05641209],
       [ 0.28178222,  1.80827782,  0.21091843,  0.41983488],
       [ 1.48860113,  0.28056916, -0.1854228 ,  0.68507538],
       [ 1.72745071,  0.28056916, -0.50249579,  0.70275808],
       [ 1.31260671,  0.86255341, -0.42322754, -0.58807905],
       [ 1.0611861 , -0.37416312, -1.13664176,  0.47288298],
       [ 1.36289083, -0.26504107, -1.13664176,  1.4100661 ],
       [ 1.38803289, -0.19229304, -0.81956877, -0.02223264],
       [ 0.92290477,  0.1350731 , -0.58176403,  0.40215217],
       [ 2.1800078 ,  0.06232507,  0.52799142,  2.17042222],
       [ 1.71487968,  0.02595105, -0.58176403,  2.43566272],
       [ 0.7720524 ,  1.18991955, -0.50249579, -0.21674234],
       [ 1.61431143,  1.26266758, -0.26469105,  0.68507538],
       [ 1.02347301,  0.89892743,  0.29018668,  0.24300787],
       [ 1.4760301 ,  0.38969121, -0.34395929,  0.49056568],
       [ 0.78462343,  0.68068333, -1.53298299,  0.13691167],
       [ 1.31260671, -0.3377891 , -0.97810527,  0.91495049],
       [-0.10791972,  1.00804947, -0.89883702,  0.70275808],
       [ 0.87262064, -0.04679698, -0.74030053,  0.18995977],
       [-0.20848797,  0.53518727, -0.81956877, -0.21674234],
       [ 0.60862901,  0.86255341, -0.66103228,  0.13691167],
       [ 0.04293264,  3.08136836,  0.84506441,  0.59666188],
       [ 0.47034767,  0.89892743, -0.1854228 , -0.23442504],
       [ 0.3572084 , -0.84702532, -0.74030053, -0.41125204],
       [ 1.07375713,  1.55365971,  0.05238194,  0.31373867],
       [ 1.26232258, -0.59240721, -0.81956877,  0.70275808],
       [ 0.8977627 ,  1.18991955, -0.58176403,  1.4100661 ],
       [ 0.70919725, -0.04679698, -1.13664176,  0.64970998],
       [ 0.83490755, -0.04679698,  0.44872317,  0.68507538],
       [ 0.9354758 ,  1.18991955,  1.08286915, -0.41125204],
       [ 0.62120004,  1.00804947, -0.58176403, -0.07528074],
       [ 0.58348695,  0.1350731 , -0.81956877,  0.49056568],
       [ 0.33206634,  1.69915577, -0.1854228 , -0.39356934],
       [ 0.04293264,  0.64430932, -0.58176403, -0.25210774],
       [ 0.0680747 , -0.99252138, -0.66103228, -0.37588664],
       [ 1.51374319,  0.49881325, -1.29517825,  0.87958509],
       [ 0.68405519, -0.22866706, -0.1854228 ,  1.3393353 ],
       [ 0.49548973, -0.91977335, -0.74030053, -0.18137694],
       [ 1.08632816,  0.78980538, -1.53298299,  0.20764247],
       [ 0.28178222, -0.30141509, -0.34395929,  0.13691167],
       [ 0.04293264, -0.99252138, -0.66103228,  0.79117158],
       [ 1.50117216,  0.24419515, -0.50249579, -0.58807905],
       [ 1.71487968, -0.3377891 , -0.74030053,  1.07409479],
       [ 1.11147022, -0.91977335, -1.21591001,  0.98568129],
       [ 1.36289083,  0.09869908, -0.34395929,  1.4100661 ],
       [ 1.16175434, -0.37416312, -0.34395929,  0.87958509],
       [ 0.04293264, -1.21076548, -1.53298299,  2.34724922],
       [ 1.02347301,  0.82617939, -1.13664176,  1.25092179],
       [ 1.01090198,  0.17144711, -0.34395929,  0.50824838],
       [ 0.94804683,  1.11717152,  0.21091843,  0.17227707],
       [ 0.91033373, -0.44691115, -1.21591001,  0.06618087],
       [ 0.68405519,  0.31694318, -1.29517825,  1.533845  ],
       [ 1.51374319, -0.26504107, -0.81956877,  0.79117158],
       [ 0.34463737,  1.11717152, -0.42322754,  0.13691167],
       [ 0.88519167,  0.46243924, -1.3744465 ,  0.80885428],
       [-0.81189742, -3.68419854, -0.66103228, -2.05574318],
       [-0.86218154, -0.3377891 ,  2.11335635, -2.07342588],
       [-0.4724796 , -1.28351351,  1.32067389, -1.70208917],
       [ 0.82233652, -1.64725366, -0.34395929, -1.50757947],
       [-0.81189742, -0.77427729, -1.3744465 ,  0.50824838],
       [-1.06331803,  0.57156129,  0.68652791, -0.97709846],
       [-0.81189742,  0.68068333,  0.05238194,  0.87958509],
       [ 0.11835882, -2.44748201, -0.81956877,  1.23323909],
       [-0.81189742, -1.64725366, -0.74030053, -0.95941576],
       [ 0.40749252, -0.04679698,  1.47921038, -2.05574318],
       [-1.01303391, -2.26561193, -1.77078773,  1.6222585 ],
       [ 1.0611861 ,  1.0807975 , -1.21591001,  0.50824838],
       [ 0.59605798, -0.48328517, -0.74030053, -0.97709846],
       [-0.03249354,  0.82617939, -1.21591001,  0.66739268],
       [-1.32730967, -0.26504107, -1.85005598,  0.11922897],
       [-1.70444058, -1.64725366, -0.1854228 , -0.76490605],
       [ 0.01779058, -2.41110799, -0.97810527, -0.21674234],
       [-1.47816203, -0.51965918,  0.52799142, -1.11856006],
       [-0.86218154, -1.53813162, -0.10615455,  2.08200871],
       [-0.39705342,  0.09869908,  0.52799142,  0.64970998],
       [-1.27702554, -1.35626154, -0.50249579, -0.26979044],
       [-0.37191136, -0.62878123, -0.81956877,  0.33142137],
       [-1.1764573 ,  0.49881325,  0.29018668, -0.32283854],
       [ 0.04293264, -0.19229304,  1.95481986,  0.06618087],
       [-1.47816203,  0.75343136, -1.13664176,  1.357018  ],
       [-0.43476651, -0.48328517, -0.50249579, -0.21674234],
       [-1.07588906, -0.22866706,  0.52799142, -0.03991534],
       [-1.71701161,  0.89892743,  0.29018668, -0.42893474],
       [-1.72958264,  0.31694318,  0.92433265, -0.41125204],
       [-1.1764573 , -0.26504107,  0.44872317, -0.35820394],
       [-1.1764573 , -0.19229304,  1.24140564,  0.10154627],
       [-1.27702554,  0.17144711,  1.08286915,  0.08386357],
       [-0.40962445, -0.41053713,  1.71701512,  0.06618087],
       [-0.91246566, -0.5560332 , -0.89883702,  0.72044078],
       [-1.7547247 , -0.3377891 , -1.53298299, -0.41125204],
       [-1.51587512,  1.33541561, -1.77078773, -0.03991534],
       [-0.91246566, -1.42900957, -0.58176403,  0.33142137],
       [-0.81189742, -0.99252138, -0.97810527,  0.64970998],
       [-0.91246566, -0.59240721,  0.68652791,  2.17042222],
       [-1.1764573 , -2.44748201, -0.81956877, -0.32283854],
       [-0.52276372, -1.7200017 , -0.58176403, -0.41125204],
       [-0.635903  , -1.42900957, -0.34395929, -0.18137694],
       [-0.74904227, -0.37416312,  2.35116109, -0.28747314],
       [-0.96274979, -0.91977335,  0.05238194,  0.08386357],
       [-0.37191136, -0.3377891 ,  0.92433265,  0.08386357],
       [-1.00046288, -1.57450563,  0.21091843,  0.87958509],
       [-1.76729573,  1.18991955, -0.58176403,  1.6045758 ],
       [-1.95586118, -2.01099382, -0.97810527,  3.53199015],
       [-0.62333197, -0.73790328, -0.81956877, -0.64112715],
       [-1.57873027,  1.99014789,  1.87555161, -0.94173306],
       [-2.01871633,  0.46243924,  0.44872317, -0.25210774],
       [-1.1764573 ,  0.46243924,  0.52799142, -0.95941576],
       [-2.49641549, -0.62878123,  1.24140564,  0.75580618],
       [-1.50330409, -1.39263556, -0.50249579, -0.09296344],
       [-0.74904227, -0.66515524, -0.1854228 ,  0.04849817],
       [-0.30905621, -1.42900957,  0.52799142, -1.33075247],
       [-1.27702554, -1.35626154,  0.05238194,  0.50824838],
       [-1.83015088,  3.11774238,  0.84506441,  0.50824838],
       [-0.74904227,  1.2990416 ,  0.52799142,  0.22532517],
       [ 0.04293264, -0.88339934, -0.50249579,  0.75580618],
       [-1.44044894,  0.06232507, -1.21591001,  2.34724922],
       [-1.18902833, -0.73790328,  0.05238194, -0.41125204],
       [-0.73647124, -0.30141509,  0.21091843,  0.33142137],
       [-1.54101718,  1.48091168,  1.71701512,  0.31373867],
       [-0.81189742, -0.26504107,  0.29018668,  0.56129648],
       [-1.22674142,  0.02595105,  0.44872317, -0.41125204],
       [-0.19591693, -0.19229304, -1.21591001, -1.13624276],
       [-0.17077487,  0.09869908, -0.97810527, -1.33075247],
       [-0.25877209,  0.09869908, -0.74030053, -1.33075247],
       [-0.39705342, -0.04679698, -1.53298299, -1.31306976],
       [-0.635903  , -0.44691115,  1.87555161, -0.58807905],
       [-0.52276372, -0.62878123,  2.11335635, -1.13624276],
       [-0.96274979,  0.6079353 ,  1.32067389, -1.38380057],
       [-0.61076094,  0.97167546,  2.11335635, -0.85331955],
       [ 0.59605798, -0.66515524,  1.71701512, -1.24233896],
       [-0.221059  ,  0.86255341,  1.32067389, -1.36611787],
       [-0.10791972,  1.18991955,  1.32067389, -1.47221407],
       [ 0.43263458, -0.08317099,  0.05238194, -1.66672377],
       [ 0.63377107,  1.26266758,  1.08286915, -1.82586808],
       [ 0.75948137, -0.08317099,  0.84506441, -0.99478116],
       [-0.96274979, -0.62878123, -0.58176403, -0.78258875],
       [ 0.18121398, -0.81065131,  0.52799142, -0.49966555],
       [ 1.08632816, -0.51965918,  0.29018668, -1.59599297],
       [-0.1833459 ,  0.38969121,  0.84506441, -1.27770436],
       [ 0.38235046,  0.02595105,  0.68652791, -0.58807905],
       [ 0.08064573, -0.04679698, -0.1854228 , -0.78258875],
       [ 0.60862901,  0.89892743, -1.13664176, -0.58807905],
       [-0.28391415,  0.38969121, -0.97810527, -0.57039635],
       [ 0.11835882,  1.37178963, -0.81956877, -0.03991534],
       [ 0.26921119, -0.3377891 ,  1.95481986,  0.50824838],
       [-0.54790578, -0.99252138,  1.32067389, -0.32283854],
       [ 0.19378501, -0.19229304,  1.95481986, -0.05759804],
       [ 1.03604404,  0.02595105,  0.92433265, -0.03991534],
       [-0.71132918,  0.97167546,  2.11335635, -0.78258875],
       [ 1.66459556,  1.18991955,  1.32067389,  1.97591251],
       [ 0.58348695,  0.97167546,  1.24140564,  1.25092179],
       [-0.82446845,  0.02595105,  1.08286915, -0.95941576],
       [ 0.84747858,  0.6079353 ,  1.08286915, -1.38380057],
       [-0.20848797,  0.75343136,  1.87555161, -1.10087736],
       [-0.07020663, -0.08317099,  0.29018668, -1.13624276],
       [ 0.96061786, -0.26504107,  0.36945493, -0.97709846],
       [ 0.8977627 , -0.41053713,  1.24140564, -0.76490605],
       [ 0.54577386,  0.82617939,  0.52799142, -0.21674234],
       [-0.24620106, -0.26504107,  0.29018668, -1.08319466],
       [ 0.70919725,  1.15354554,  0.21091843, -0.07528074],
       [ 0.4829187 ,  1.7719038 , -0.74030053, -0.83563685],
       [-1.02560494, -0.19229304,  0.29018668, -1.50757947],
       [-0.30905621, -0.3377891 ,  0.92433265, -1.66672377],
       [ 1.43831701,  0.38969121,  0.60725967, -0.60576175],
       [ 0.87262064,  0.28056916,  1.24140564, -0.92405036],
       [ 0.4829187 ,  0.38969121,  0.52799142, -0.30515584],
       [ 0.31949531, -0.41053713,  0.52799142, -0.41125204],
       [ 0.19378501, -0.01042296,  1.32067389, -0.21674234],
       [ 1.40060392,  1.33541561,  1.55847863, -0.41125204]])

In [32]:
wine_tt_sc=pd.DataFrame(wine_sc,columns=wine_xx.columns)    # 스케일링 된 값을 데이터프레임 형식으로 만듦
wine_tt_sc

      alcohol       ash  nonflavanoid_phenols  proanthocyanins
0    1.526314  0.207821             -0.661032         1.250922
1    0.181214  1.080798             -0.502496         2.170422
2    1.702309  0.462439             -0.978105         1.056412
3    0.281782  1.808278              0.210918         0.419835
4    1.488601  0.280569             -0.185423         0.685075
..        ...       ...                   ...              ...
166  0.872621  0.280569              1.241406        -0.924050
167  0.482919  0.389691              0.527991        -0.305156
168  0.319495 -0.410537              0.527991        -0.411252
169  0.193785 -0.010423              1.320674        -0.216742
170  1.400604  1.335416              1.558479        -0.411252

[171 rows x 4 columns]

In [35]:
kmeans.fit(wine_tt_sc)
wine['cluster3']=kmeans.labels_
wine.groupby(['class','cluster3'])['ash'].count()

/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

class  cluster3
0      0            5
       1            1
       2           51
1      0           39
       1           25
       2            2
2      0            5
       1           36
       2            7
Name: ash, dtype: int64

In [36]:
wine

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,class,cluster,cluster2,cluster3
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,0,0,1,2
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,0,0,1,2
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,0,0,1,2
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,0,1,1,2
5,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450,0,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,2,1,2,1
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,2,1,2,1
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,2,1,2,1
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,2,1,2,1
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,2,2,1,1

- 거리기반으로 민감하게 움직이기 때문에 스케일링과 변수들의 이상치 등을 고려하여 군집을 만들어야 한다.
- 몇 개의 군집이 적정한지 -> inertia, 실루엣 점수, 엘보우 점수
- but 점수만 보지 말고 시각화도 해봐야 한다.


---

- 4차원 이상은 시각화로 이해할 수 없다.
- 그래서 차원축소(PCA)를 하는 것