### 결측 데이터 처리
- 결측값이 무작위로 있는지, 특정 변수와 관계가 있는지 확인
- 대체/제거

In [4]:
import pandas as pd

file_path='C:/python/python/python_data/6장데이터/bicycle.csv'
df=pd.read_csv(file_path, engine='python',encoding='euc-kr')
df

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-23220,2019-11-01 8:48,646,장한평역 1번출구 (국민은행앞),3.0,2019-11-01 9:01,3,중랑센터,7.0,12.0,1100.0
1,SPB-16216,2019-11-04 8:38,646,장한평역 1번출구 (국민은행앞),2.0,2019-11-04 8:56,3,중랑센터,2.0,7.0,1420.0
2,SPB-21097,2019-11-04 8:46,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-04 8:57,3,중랑센터,7.0,10.0,NaN
3,SPB-22292,2019-11-05 8:34,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-05 8:45,3,중랑센터,NaN,10.0,1380.0
4,SPB-07935,2019-11-05 12:29,512,뚝섬역 1번 출구 옆,11.0,2019-11-05 12:39,3,중랑센터,7.0,10.0,1650.0
...,...,...,...,...,...,...,...,...,...,...,...
415,SPB-12116,2019-11-15 4:22,112,극동방송국 앞,5.0,2019-11-15 4:33,101,(구)합정동 주민센터,1.0,11.0,2200.0
416,SPB-17768,2019-11-15 9:31,103,망원역 2번출구 앞,14.0,2019-11-15 9:37,101,(구)합정동 주민센터,NaN,5.0,NaN
417,SPB-18841,2019-11-15 20:40,113,홍대입구역 2번출구 앞,24.0,2019-11-15 20:53,101,(구)합정동 주민센터,1.0,12.0,2280.0
418,SPB-24467,2019-11-15 21:55,152,마포구민체육센터 앞,18.0,2019-11-15 22:05,101,(구)합정동 주민센터,1.0,10.0,1180.0
419,SPB-17570,2019-11-15 22:16,391,정동길입구,7.0,2019-11-15 23:04,101,(구)합정동 주민센터,5.0,48.0,8100.0

In [7]:
# 결측 데이터 확인

df.isnull()  # 결측값이 있는 곳에 True
df.notnull()  # 결측값이 있는 곳에 False

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,False
3,True,True,True,True,True,True,True,True,False,True,True
4,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...
415,True,True,True,True,True,True,True,True,True,True,True
416,True,True,True,True,True,True,True,True,False,True,False
417,True,True,True,True,True,True,True,True,True,True,True
418,True,True,True,True,True,True,True,True,True,True,True
419,True,True,True,True,True,True,True,True,True,True,True

In [23]:
# 결측 데이터 개수 확인
df.isnull().sum()  # 열
df.isnull().sum(1)  # 행

df.notnull().sum()  # 열
df.notnull().sum(1)  #행

자전거번호       0
대여일시        0
대여소번호       0
대여소명        0
대여거치대      24
반납일시        0
반납대여소번호     0
반납대여소명      0
반납거치대      11
이용시간       15
이용거리       16
dtype: int64

In [21]:
# 결측 데이터 제거
df_drop_allrow=df.dropna(axis=0)
df_drop_allrow.isnull().sum()  # 결측값 모두 없어진 것 확인

# 결측 데이터가 있는 열 제거
df_drop_allcol=df.dropna(axis=1)
df_drop_allcol.isnull().sum()  # 결측값이 있는 열을 아예 삭제해버림

자전거번호      0
대여일시       0
대여소번호      0
대여소명       0
반납일시       0
반납대여소번호    0
반납대여소명     0
dtype: int64

In [37]:
df['대여거치대'].dropna()
df[['대여거치대','반납거치대','이용시간']].dropna()  # 한 번에 여러 열에 해당하는 결측치를 없앨 수도 있음
df[['대여소번호','반납거치대','이용시간']].dropna(axis=1)  # 결측치가 있는 열 없애버림

     대여소번호
0      646
1      646
2      646
3      646
4      512
..     ...
415    112
416    103
417    113
418    152
419    391

[420 rows x 1 columns]